### ISSUE TITLE
Building uber-jar

### ISSUE THREAD

**Issue by mingen-pan** [googleinterns/calcite#101]
Currently, the way to import our Calcite is to pack it as jar. However, the jar does not include every dependency of the Calcite. Would it be reasonable to to modify the building process to include every dependency in the jar?

**Comment by dasch-1** [comment]
Hi Mingen, sorry I just noticed this issue. We haven't been using GitHub issues in the past, but it could be useful going forward.

As to your question: I don't see any philosophical concerns with having a separate gradlew build rule to pull in all of Calcite's dependencies into the jar. @michaelvdow and @AndrewPochapsky, WDYT?

**Comment by dasch-1** [comment]
Closing this out since it seems like Mingen might be going with a different approach for his project. However, if the plan changes, we can always reopen.
